import type { Command } from "commander";
import { c } from "../../utils/colors.js";

/**
 * Shell completion scripts generated from the live commander program, so
 * they can never drift from the actual command surface.
 *
 *   qring completion bash >> ~/.bashrc            (or bash-completion dir)
 *   qring completion zsh  > ~/.zsh/completions/_qring
 *   qring completion fish > ~/.config/fish/completions/qring.fish
 */

interface CmdInfo {
  name: string;
  aliases: string[];
  description: string;
  options: Array<{ flag: string; description: string }>;
  subcommands: CmdInfo[];
}

function collect(cmd: Command): CmdInfo {
  return {
    name: cmd.name(),
    aliases: cmd.aliases(),
    description: cmd.description(),
    options: cmd.options
      .map((o) => ({ flag: o.long ?? o.short ?? "", description: o.description ?? "" }))
      .filter((o) => o.flag.startsWith("--")),
    subcommands: cmd.commands
      .filter((s) => s.name() !== "help")
      .map((s) => collect(s as Command)),
  };
}

const sanitize = (s: string) =>
  s.replace(/['"`$\\]/g, "").replace(/[:[\]]/g, " ").replace(/\s+/g, " ").trim();

function bashScript(cmds: CmdInfo[]): string {
  const names = cmds.flatMap((x) => [x.name, ...x.aliases]).join(" ");
  const cases = cmds
    .map((x) => {
      const label = [x.name, ...x.aliases].join("|");
      const opts = [...x.options.map((o) => o.flag), "--json"].join(" ");
      const subs = x.subcommands.map((s) => s.name).join(" ");
      const subCase = subs
        ? `\n      if [ "$COMP_CWORD" -eq 2 ]; then COMPREPLY=( $(compgen -W "${subs}" -- "$cur") ); return; fi`
        : "";
      return `    ${label})${subCase}\n      opts="${opts}" ;;`;
    })
    .join("\n");

  return `# bash completion for qring — generated by \`qring completion bash\`
_qring_completions() {
  local cur cmd opts
  cur="\${COMP_WORDS[COMP_CWORD]}"
  cmd="\${COMP_WORDS[1]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "${names}" -- "$cur") )
    return
  fi
  opts="--json --help"
  case "$cmd" in
${cases}
  esac
  case "$cur" in
    -*) COMPREPLY=( $(compgen -W "$opts --help" -- "$cur") ) ;;
  esac
}
complete -o default -F _qring_completions qring
`;
}

function zshScript(cmds: CmdInfo[]): string {
  const items = cmds
    .map((x) => `    '${x.name}:${sanitize(x.description)}'`)
    .join("\n");
  const cases = cmds
    .map((x) => {
      const label = [x.name, ...x.aliases].join("|");
      const words = [
        ...x.subcommands.map((s) => s.name),
        ...x.options.map((o) => o.flag),
        "--json",
      ].join(" ");
      return `    ${label}) compadd -- ${words} ;;`;
    })
    .join("\n");

  return `#compdef qring
# zsh completion for qring — generated by \`qring completion zsh\`
_qring() {
  local -a commands
  commands=(
${items}
  )
  if (( CURRENT == 2 )); then
    _describe 'command' commands
    return
  fi
  case $words[2] in
${cases}
  esac
}
_qring "$@"
`;
}

function fishScript(cmds: CmdInfo[]): string {
  const lines: string[] = [
    "# fish completion for qring — generated by `qring completion fish`",
    "complete -c qring -f",
  ];
  const allNames = cmds.flatMap((x) => [x.name, ...x.aliases]);
  for (const x of cmds) {
    for (const name of [x.name, ...x.aliases]) {
      lines.push(
        `complete -c qring -n "not __fish_seen_subcommand_from ${allNames.join(" ")}" -a ${name} -d "${sanitize(x.description)}"`,
      );
    }
    for (const s of x.subcommands) {
      lines.push(
        `complete -c qring -n "__fish_seen_subcommand_from ${x.name}" -a ${s.name} -d "${sanitize(s.description)}"`,
      );
    }
    for (const o of [...x.options, { flag: "--json", description: "Output as JSON" }]) {
      lines.push(
        `complete -c qring -n "__fish_seen_subcommand_from ${x.name}" -l ${o.flag.slice(2)} -d "${sanitize(o.description)}"`,
      );
    }
  }
  return lines.join("\n") + "\n";
}

export function registerCompletionCommand(program: Command): void {
  program
    .command("completion <shell>")
    .description("Print a shell completion script (bash, zsh, fish)")
    .action((shell: string) => {
      const cmds = program.commands
        .filter((s) => s.name() !== "help" && s.name() !== "completion")
        .map((s) => collect(s as Command));

      if (shell === "bash") process.stdout.write(bashScript(cmds));
      else if (shell === "zsh") process.stdout.write(zshScript(cmds));
      else if (shell === "fish") process.stdout.write(fishScript(cmds));
      else {
        console.error(c.red(`Unknown shell "${shell}" — expected bash, zsh, or fish`));
        process.exitCode = 1;
      }
    });
}
